title: cborg
email: cborg@citrine.io
description: >
  Remember the time he ate my goldfish? And you lied and said I never had goldfish.
  Then why did I have the bowl, Bart? Why did I have the bowl?
baseurl: "https://ckborg.github.io/"
url: "https://ckborg.github.io/"
twitter_username: ckhborg
github_username:  ckborg

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji

exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
